#!/bin/bash

repo="ocawesome101/oc-refinement"
name="refinement"
path="/tmp/$name"

printf "downloading source\n"
rm -rf $path
git clone https://github.com/$repo $path
if ! [ -e /tmp/external ]; then
  git clone https://github.com/ocawesome101/ulos-external /tmp/external
else
  oldpwd=$PWD
  cd /tmp/external
  git pull
  cd $oldpwd
fi

#printf "downloading build agent\n"
#wget -q https://raw.githubusercontent.com/ocawesome101/oc-ulos/master/build -O $path/build

printf "building\n"
oldpwd=$PWD
cd $path

imods=$(echo $IMODS | lua -e 'print((io.read():gsub(",", "\n")))')
rm -f includes.lua && touch includes.lua
for mod in $imods; do
  printf -- "--#include \"%s.lua\"\n" $mod >> includes.lua
done

$PREPROCESSOR init.lua refinement.lua

cd $oldpwd

mkdir -p files/sbin
cp -v $path/refinement.lua files/sbin/init.lua
cp -r /tmp/external/coresvc/* files/*/
