#!/bin/bash

repo="ocawesome101/oc-refinement"
name="refinement"
path="/tmp/$name"

printf "downloading source\n"
rm -rf $path
git clone https://github.com/$repo $path
if ! [ -e /tmp/external ]; then
  git clone https://github.com/ocawesome101/ulos-external /tmp/external
else
  oldpwd=$PWD
  cd /tmp/external
  git pull
  cd $oldpwd
fi

printf "building\n"
oldpwd=$PWD
cd $path

./build.sh

cd $oldpwd

rm -rf files && mkdir -p files/sbin
cp -v $path/refinement.lua files/sbin/init.lua
cp -r /tmp/external/coresvc/* files/
