#!/bin/bash

repo="ocawesome101/tle"
name="tle"
path="/tmp/$name"

printf "downloading source\n"
if ! [ -e $path ]; then
  git clone https://github.com/$repo $path
else
  oldpwd=$PWD
  cd $path
  git pull
  cd $oldpwd
fi

printf "building\n"
oldpwd=$PWD
cd $path
lua standalone.lua
cd $oldpwd

rm -rf files && mkdir -p files/bin files/usr/share/
cp -r /tmp/$name/tle files/bin/tle.lua
cp -r /tmp/$name/syntax files/usr/share/VLE
