#!/bin/bash

repo="ocawesome101/oc-cynosure"
name="cynosure"
path="/tmp/$name"

printf "downloading source\n"
if ! [ -e $path ]; then
  git clone https://github.com/$repo $path
else
  oldpwd=$PWD
  cd $path
  git pull
  cd $oldpwd
fi

printf "building\n"
oldpwd=$PWD
cd $path

./build.sh

cd $oldpwd

rm -rf files && mkdir -p files/boot
cp -v $path/kernel.lua files/boot/cynosure.lua
