#!/bin/bash

repo="ocawesome101/oc-cynosure"
name="cynosure"
path="/tmp/$name"

printf "downloading source\n"
if ! [ -e $path ]; then
  git clone https://github.com/$repo $path
else
  oldpwd=$PWD
  cd $path
  git pull
  cd $oldpwd
fi

#printf "downloading build agent\n"
#wget -q https://raw.githubusercontent.com/ocawesome101/oc-ulos/master/build -O $path/build

printf "building"
oldpwd=$PWD
cd $path

source .buildconfig
kmods=$(echo $KMODS | lua -e 'print((io.read():gsub(",", "\n")))')
rm -f includes.lua && touch includes.lua
for mod in $kmods; do
  printf -- "--#include \"%s.lua\"\n" $mod >> includes.lua
done

$PREPROCESSOR init.lua kernel.lua

cd $oldpwd

mkdir -p files/boot
cp -v $path/kernel.lua files/boot/cynosure.lua
