#!/bin/bash

repo="ocawesome101/ulos-external"
name="external"
path="/tmp/$name"
subdir="usysd"

printf "downloading source\n"
if ! [ -e $path ]; then
  git clone https://github.com/$repo $path
else
  oldpwd=$PWD
  cd $path
  git pull
fi

cd $path/$subdir
./build.sh
cd $oldpwd

rm -rf files && mkdir -p files
cp -rv /tmp/external/$subdir/out/* files/
