#!/bin/bash

repo="ocawesome101/ulos-external/master"
baseurl="https://raw.githubusercontent.com/$repo"
outpath="files/"

mkdir -p files

download() {
  printf "downloading $baseurl/$1..."
  wget -q "$baseurl/$1" -O $outpath/$2
  printf "done\n"
}

download cldr/init.lua init.lua
